name = "hugo-theme-jinhakim"
license = "MIT"
licenselink = "https://github.com/phi-jkim/hugo-theme-jinhakim/LICENSE"
description = "Simplistic and efficient hugo design for blogs & resume"
homepage = "https://github.com/phi-jkim/hugo-theme-jinhakim"
tags = []
features = [] 
min_version = "0.41.0"

[author]
  name = "Jinha Kim"
  homepage = "URL to your homepage" 